services:
  - type: web
    name: digital-marketing
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn digital.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: digital.settings
    autoDeploy: true
    migrateCommand: python manage.py migrate